--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Serverfarmer02/ChatEmotes-PE
build-by-default: true
branches:
- main
projects:
  ChatEmotes-PE:
    path: "https://raw.githubusercontent.com/eyNoah/ChatEmotes-PE/main/icon.gif"
    icon: "https://raw.githubusercontent.com/eyNoah/ChatEmotes-PE/main/icon.gif"
...
