--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Serverfarmer02/ChatEmotes-PE
build-by-default: true
branches:
- main
projects:
  ChatEmotes-PE:
    path: ""
    icon: "Lonley.jpg"
...
